In [1]:
import pandas as pd
import numpy as np
dataset = pd.read_csv (r'C:/Users/Boaz/Documents/new_data_label.csv')
del dataset['Unnamed: 0']
del dataset['event_date']
# dataset.loc[dataset['labels'] != 0, 'labels'] = 1
# dataset.loc[dataset['labels'] == 0, 'labels'] = 0
print(dataset)


data = pd.read_csv(r'C:/Users/Boaz/Documents/new_data_label.csv')
del data['Unnamed: 0']
del data['event_date']
del data['labels']
print(data)

       response_time  response_size  session_duration  response_errorcode_num  \
0             718444      750197670                 2                       0   
1            1051741      794574705                 1                       0   
2             666003      445975743                 0                       0   
3             939968      342481634                 0                       0   
4            1059742      316304423                 0                       0   
...              ...            ...               ...                     ...   
61339        1654815      986044166                 2                       0   
61340        1080735      942590486                 0                       0   
61341        1266569      887658828                 4                       0   
61342         555966      850409314                 0                       0   
61343        1603774     1005933723                 2                       0   

       response_failure_num

In [2]:
import pandas as pd
import numpy as np
datasets = pd.read_csv (r'C:/Users/Boaz/Documents/new_data_label.csv')
del datasets['Unnamed: 0']
del datasets['event_date']
print(datasets)


datas = pd.read_csv(r'C:/Users/Boaz/Documents/new_data_label.csv')
del datas['Unnamed: 0']
del datas['event_date']
del datas['labels']
print(datas)

       response_time  response_size  session_duration  response_errorcode_num  \
0             718444      750197670                 2                       0   
1            1051741      794574705                 1                       0   
2             666003      445975743                 0                       0   
3             939968      342481634                 0                       0   
4            1059742      316304423                 0                       0   
...              ...            ...               ...                     ...   
61339        1654815      986044166                 2                       0   
61340        1080735      942590486                 0                       0   
61341        1266569      887658828                 4                       0   
61342         555966      850409314                 0                       0   
61343        1603774     1005933723                 2                       0   

       response_failure_num

In [32]:
datasets['labels'][:10]

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: labels, dtype: int64

In [3]:
Y= datasets['labels']
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

dummy_y

array([[1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]], dtype=float32)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(datas, dummy_y, test_size=0.3,random_state=109,stratify=dataset['labels']) # 70% training and 30% test

In [5]:

X_train.shape
y_train.shape

(42940, 6)

In [36]:
y_test[:10]

array([[1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]], dtype=float32)

In [17]:
from keras.datasets import mnist 
from keras.models import Model 
from keras.layers import Input, Dense 
from keras.utils import np_utils 
import numpy as np
import time
t = time.time()
input_img = Input(shape=(5,))

x = Dense(5, activation='relu')(input_img)

encoded = Dense(5, activation='relu')(x)

encoded1 = Dense(3, activation='relu')(encoded)

encoded2 = Dense(2, activation='relu')(encoded1)

y = Dense(6, activation='relu')(x)

decoded = Dense(5, activation='relu')(y)

decoded1 = Dense(3, activation='relu')(decoded)

decoded2 = Dense(2, activation='relu')(decoded1)


z = Dense(5, activation='sigmoid')(decoded)
model = Model(input_img, z)

model.compile(optimizer='adam', loss='mse') # reporting the accuracy

model.fit(X_train, X_train,
      epochs=10,
      batch_size=128,
      shuffle=True,
      validation_data=(X_test, X_test))

mid = Model(input_img, y)
reduced_representation =mid.predict(X_test)

out = Dense(6, activation='softmax')(y)
reduced = Model(input_img, out)
reduced.compile(loss='categorical_crossentropy',
          optimizer='adam', 
          metrics=['accuracy']) 

reduced.fit(X_train, y_train,
      epochs=30,
      batch_size=128,
      shuffle=True,
      validation_data=(X_test, y_test))

scores = reduced.evaluate(X_test, y_test, verbose=1) 
elapsed = time.time() - t
print("Accuracy: ", scores[1])

Epoch 1/10
336/336 [==============================] - 13s 2ms/step - loss: 180440557939386880.0000 - val_loss: 192403556924391424.0000
Epoch 2/10
336/336 [==============================] - 0s 791us/step - loss: 179391811321173792.0000 - val_loss: 192403556924391424.0000
Epoch 3/10
336/336 [==============================] - 0s 821us/step - loss: 177037922760272896.0000 - val_loss: 192403556924391424.0000
Epoch 4/10
336/336 [==============================] - 0s 812us/step - loss: 177308897230159200.0000 - val_loss: 192403556924391424.0000
Epoch 5/10
336/336 [==============================] - 0s 766us/step - loss: 187967058246555968.0000 - val_loss: 192403556924391424.0000
Epoch 6/10
336/336 [==============================] - 0s 763us/step - loss: 187233944237809152.0000 - val_loss: 192403556924391424.0000
Epoch 7/10
336/336 [==============================] - 0s 771us/step - loss: 182757763477740960.0000 - val_loss: 192403556924391424.0000
Epoch 8/10
336/336 [=============================

In [49]:
y_pred = model.predict(X_test)
y_pred_new=  np.argmax(y_pred,axis=1)
y_pred_new

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [50]:
count = 0
for x in y_pred_new:
    if x != 0:
        #print(x)
        count += 1
print(count)

0


In [51]:
# ONE HOT ENCODER BACK TO INTEGERS
y_test
a = y_test
y_test_new = [np.where(r==1)[0][0] for r in a]
for i in range(len(y_test_new)):
    if y_test_new[i] == 2:
        y_test_new[i] = 3
        
    elif y_test_new[i] == 3:
        y_test_new[i] = 5
        
    elif y_test_new[i] == 4:
        y_test_new[i] = 6
        
    elif y_test_new[i] == 5:
        y_test_new[i] = 7

y_test_new

[0,
 0,
 0,
 0,
 3,
 6,
 1,
 0,
 0,
 0,
 0,
 0,
 3,
 0,
 1,
 0,
 0,
 0,
 3,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 0,
 1,
 0,
 0,
 0,
 3,
 0,
 0,
 0,
 6,
 0,
 1,
 0,
 0,
 3,
 0,
 3,
 5,
 3,
 0,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 3,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 6,
 0,
 3,
 0,
 6,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 6,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 0,
 3,
 0,
 0,
 0,
 3,
 3,
 0,
 0,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 0,
 0,
 7,
 1,
 0,
 6,
 0,
 0,
 0,
 3,
 3,
 0,
 6,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 3,
 0,
 0,
 0,
 0,
 0,
 6,
 0,
 6,
 0,
 1,
 0,
 3,
 0,
 0,
 3,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 6,
 0,
 0,
 0,
 0,
 0,
 6,
 6,
 0,
 3,
 0,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 6,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 6,
 0,
 0,
 0,
 6,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 0,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 0,


In [52]:
for i in range(len(y_pred_new)):
    if y_pred_new[i] == 0:
        y_pred_new[i] = 0
    elif y_pred_new[i] == 1:
        y_pred_new[i] = 1
    elif y_pred_new[i] == 2:
        y_pred_new[i] = 3
        
    elif y_pred_new[i] == 3:
        y_pred_new[i] = 5
        
    elif y_pred_new[i] == 4:
        y_pred_new[i] = 6
        
    elif y_pred_new[i] == 5:
        y_pred_new[i] = 7


In [53]:
count = 0
for x in y_pred_new:
    if x != 0:
        count += 1
print(count)

0


In [55]:
from sklearn import metrics
print("F1:",metrics.f1_score(y_test_new,y_pred_new,labels=[0,1,3,5,6,7],average='weighted'))
print('\nDuration in seconds:')
print(elapsed)

F1: 0.6673494324675149

Duration in seconds:
12.9117910861969
